/*
 * hangjituEast.java
 *
 * Created on __DATE__, __TIME__
 */

package com.xiaobei.GPS;

/**
 *
 * @author  __USER__
 */
public class hangjituEast extends javax.swing.JPanel{

	/** Creates new form hangjituEast */
	public hangjituEast() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jPanel3 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jPanel4 = new javax.swing.JPanel();
		jLabel3 = new javax.swing.JLabel();
		jTextField2 = new javax.swing.JTextField();
		jPanel5 = new javax.swing.JPanel();
		jLabel4 = new javax.swing.JLabel();
		jTextField3 = new javax.swing.JTextField();
		jPanel2 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jComboBox1 = new javax.swing.JComboBox();

		setLayout(new java.awt.BorderLayout());

		jPanel1.setLayout(new java.awt.GridLayout(3, 0));

		jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(
				javax.swing.border.BevelBorder.LOWERED));
		jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER,
				5, 20));

		jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14));
		jLabel2.setText("\u9ad8\u5ea6\uff1a");
		jPanel3.add(jLabel2);

		jTextField1.setBorder(new javax.swing.border.SoftBevelBorder(
				javax.swing.border.BevelBorder.LOWERED));
		jTextField1.setPreferredSize(new java.awt.Dimension(67, 25));
		jPanel3.add(jTextField1);

		jPanel1.add(jPanel3);

		jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(
				javax.swing.border.BevelBorder.LOWERED));
		jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER,
				5, 20));

		jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14));
		jLabel3.setText("\u7ecf\u5ea6\uff1a");
		jPanel4.add(jLabel3);

		jTextField2.setBorder(new javax.swing.border.SoftBevelBorder(
				javax.swing.border.BevelBorder.LOWERED));
		jTextField2.setPreferredSize(new java.awt.Dimension(67, 25));
		jPanel4.add(jTextField2);

		jPanel1.add(jPanel4);

		jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(
				javax.swing.border.BevelBorder.LOWERED));
		jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER,
				5, 20));

		jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14));
		jLabel4.setText("\u7eac\u5ea6\uff1a");
		jPanel5.add(jLabel4);

		jTextField3.setBorder(new javax.swing.border.SoftBevelBorder(
				javax.swing.border.BevelBorder.LOWERED));
		jTextField3.setPreferredSize(new java.awt.Dimension(67, 25));
		jPanel5.add(jTextField3);

		jPanel1.add(jPanel5);

		add(jPanel1, java.awt.BorderLayout.CENTER);

		jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(
				new javax.swing.border.SoftBevelBorder(
						javax.swing.border.BevelBorder.LOWERED),
				"\u76ee\u6807\u9009\u62e9"));
		jPanel2.setPreferredSize(new java.awt.Dimension(174, 75));

		jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14));
		jLabel1.setText("\u76ee\u6807\u9009\u62e9\uff1a");
		jPanel2.add(jLabel1);

		jComboBox1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14));
		jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"目标 1", "目标 2", "目标 3", "目标 4" }));
		jComboBox1.setPreferredSize(new java.awt.Dimension(75, 23));
		jPanel2.add(jComboBox1);

		add(jPanel2, java.awt.BorderLayout.PAGE_START);
	}// </editor-fold>
	//GEN-END:initComponents

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JComboBox jComboBox1;
	private javax.swing.JLabel jLabel1;
	public static javax.swing.JLabel jLabel2;
	public static javax.swing.JLabel jLabel3;
	public static javax.swing.JLabel jLabel4;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel5;
	public static javax.swing.JTextField jTextField1;
	public static javax.swing.JTextField jTextField2;
	public static javax.swing.JTextField jTextField3;
	// End of variables declaration//GEN-END:variables
	



}